version: '3.7'

services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: 123ABC
      POSTGRES_USER: crawler
      POSTGRES_DB: crawler
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  db-web:
    image: sosedoff/pgweb
    environment:
      DATABASE_URL: postgres://crawler:123ABC@db:5432/crawler?sslmode=disable
    ports:
      - 5433:8081

volumes:
  pg-data:
